# Generated by Django 4.2.15 on 2024-08-19 03:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parking_status', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='description',
            new_name='freeSlots',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='parkingName',
        ),
        migrations.AddField(
            model_name='data',
            name='updateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
